fs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from fs import settings
from django.conf.urls.static import static
from fs.views import IndexView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # url(r'^search/', include('haystack.urls')),
    url(r'^search/',
        include('search.urls', app_name='search', namespace='search')),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^profile/',
        include('ex_user.urls', app_name='ex_user', namespace='ex_user')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^materials/',
        include('materials.urls', app_name='materials',
                namespace='materials')),
    url(r'^comments/',
        include('comments.urls', app_name='comments', namespace='comments')),
    url(r'^admin/', include(admin.site.urls)),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.conf.urls import include, url
from materials import views

urlpatterns = [
    url(r'^attribute/(?P<group_slug>[-\w]+)/(?P<slug>[\w-]+)/$', views.AttributeDetailView.as_view(), name='attribute'),
    url(r'^item/(?P<group_slug>[-\w]+(/[\w-]+)*)/(?P<slug>[-\w]+)/$',
        views.DetailItemView.as_view(), name='detail_item'),
    url(r'^group/(?P<slug>[\w-]+(/[\w-]+)*)/$',
        views.DetailGroupView.as_view(), name='detail_group'),
    url(r'^favorite_item/(?P<pk>[\d]+)/$', views.FavoriteItem.as_view(), name='favorite_item'),
    url(r'^future_item/(?P<pk>[\d]+)/$', views.FutureItem.as_view(), name='future_item'),
    url(r'^add_content_type/$', views.AddContentType.as_view(), name='add_content_type'),
    url(r'^play_video/(?P<group_slug>[-\w]+(/[\w-]+)*)/(?P<slug>[-\w]+)/$',
        views.PlayVideo.as_view(), name='play_video'),
    url(r'^vote/$', views.vote, name='vote'),
    url(r'^cancel_vote/', views.cancel_vote, name='cancel_vote'),
    url(r'^edit/(?P<slug>[-\w]+)/$', views.EditItemView.as_view(), name='item_edit'),
    url(r'^genres/$', views.show_genres),
]

materials/forms.py
__author__ = 'igor'
from comments.models import Comment
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from django import forms
from materials.models import Item
from django.contrib.admin import widgets
from materials.models import Genre
from materials.widgets import ImageWidget, MultipleChoiceWidget, DateWidget
from djangular.forms import NgFormValidationMixin, NgModelForm
from djangular.styling.bootstrap3.forms import Bootstrap3Form


class UserMeta(type(NgModelForm), type(Bootstrap3Form)):
    pass


class CommentForm(NgModelForm, NgFormValidationMixin, Bootstrap3Form):
    __metaclass__ = UserMeta

    class Meta:
        model = Comment
        fields = ['text', 'like_object']
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': _('You comment')})
        }
        error_messages = {
            'text': {
                'require': _("This field required."),
            },
        }


class EditItemForm(NgModelForm, NgFormValidationMixin, Bootstrap3Form):
    __metaclass__ = UserMeta

    class Meta:
        model = Item
        fields = [
            'title',
            'origin_title',
            'genres',
            'original_image',
            'description',
        ]
        labels = {
            'origin_title':
            _('Original name (do not fill in if the same as Russian):'),
        }
        widgets = {
            'original_image':
            ImageWidget(attrs={
                'max_width': 'auto',
                'max_height': 'auto'
            }),
            'genres':
            MultipleChoiceWidget,
            'description':
            forms.Textarea(attrs={'class': "form-control"}),
            'title':
            forms.TextInput(attrs={
                'size': 40,
                'title': _('Title'),
                'class': "form-control"
            }),
            'origin_title':
            forms.TextInput(attrs={
                'size': 40,
                'title': _('Origin title'),
                'class': "form-control"
            }),
        }

materials/views.py
from materials.models import Group, Item, Attribute, Genre
from django.db.models import Q, F
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.views.generic import View
from django.views.generic import FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin, ModelFormMixin
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json
from django.views.decorators.csrf import csrf_exempt
from materials.forms import CommentForm, EditItemForm
from django.shortcuts import redirect
from django.http import JsonResponse
from django.views.generic import TemplateView
from django.views.generic import View

ADD_TO_FAVORITES = _('Add to favorites')
FAVOURED = _('Favoured')
FUTURE = _('For the future')
ADD_TO_FUTURE = _('Add to future')


class AttributeDetailView(generic.DetailView):
    model = Attribute

    def get(self, request, *args, **kwargs):
        self.kwargs.get('slug', False)
        return super(AttributeDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AttributeDetailView, self).get_context_data(**kwargs)
        group = get_object_or_404(Group, slug=self.kwargs['group_slug'])
        queryset_attribute_value = set()

        if self.request.GET.get('attribute_value', ()):
            queryset_attribute_value = set(
                self.request.GET.get('attribute_value').split('__'))

        link = self.build_link_on_exist_data('', 'attribute')
        link = self.build_link_on_exist_data(link, 'sort')
        context['attribute_values'] = []

        for value in self.object.attribute_values.all():
            value_set = queryset_attribute_value.copy()

            if value.slug not in queryset_attribute_value:
                value_set.add(value.slug)
            else:
                value.active = True
                value_set.discard(value.slug)

            link_value = link

            if value_set:
                link_value += '&' if link else '?'
                link_value += 'attribute_value=' + '__'.join(value_set)

            value.link = '%s%s' % \
                         (reverse('materials:detail_group', kwargs={
                          'slug': group.slug_to_string()}), link_value)
            context['attribute_values'].append(value)

        link = self.build_link_on_exist_data(link, 'page')
        link = self.build_link_on_exist_data(link, 'attribute_value')
        context['back'] = '%s%s' % (reverse(
            'materials:detail_group', kwargs={'slug': group.slug_to_string()}),
            link)
        context['group'] = group
        return context

    def build_link_on_exist_data(self, link, param):
        if self.request.GET.get(param, ''):
            link += '&' if link else '?'
            link += '%s=%s' % (param, self.request.GET.get(param))
        return link


class DetailGroupView(generic.DetailView):
    model = Group

    def get(self, request, *args, **kwargs):
        if self.kwargs.get('slug', False):
            self.kwargs['slug'] = self.kwargs['slug'].split('/').pop()
        return super(DetailGroupView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetailGroupView, self).get_context_data(**kwargs)
        queryset = Item.objects.filter(Q(main_group=self.object) | Q(groups=self.object), enable=1).\
            select_related('main_group')
        context['items_popular'] = queryset.order_by('-popular')[:8]
        context['breadcrumbs'] = self.object.get_tree_group([])
        page = self.request.GET.get('page')
        queryset_attribute = set()
        queryset_attribute_value = self.request.GET.get('attribute_value', '')

        if self.request.GET.get('attribute', ()):
            queryset_attribute = set(
                self.request.GET.get('attribute').split('__'))
            queryset = queryset.filter(
                item_attr__attribute__slug__in=queryset_attribute)

        if queryset_attribute_value:
            attribute_value = set(
                self.request.GET.get('attribute_value').split('__'))
            queryset = queryset.filter(
                item_attr__attribute_values__slug__in=attribute_value)

        link = self.build_link_on_exist_data('', 'page')
        link = self.build_link_on_exist_data(link, 'sort')
        link = self.build_link_on_exist_data(link, 'attribute_value')

        for attribute in self.object.attributes.all():
            for children in attribute.children.all():
                attr_set = queryset_attribute.copy()

                if not children.attribute_values.exists():
                    if children.slug not in queryset_attribute:
                        attr_set.add(children.slug)
                    else:
                        children.active = True
                        attr_set.discard(children.slug)
                attribute_link = link

                if attr_set:
                    attribute_link += '&' if attribute_link else '?'
                    attribute_link += 'attribute=' + '__'.join(attr_set)

                if queryset_attribute_value:
                    children_attribute_value = {
                        value.slug
                        for value in children.attribute_values.all()
                    }
                    attribute_value_get = set(
                        self.request.GET.get('attribute_value').split('__'))

                    if children_attribute_value.intersection(
                            attribute_value_get):
                        children.active = True
                children.link = self.object.get_absolute_url() + attribute_link

                if children.attribute_values.exists():
                    children.link = '%s%s' % (reverse(
                        'materials:attribute',
                        kwargs={
                            'slug': children.slug,
                            'group_slug': self.object.slug
                        }), attribute_link)

        link = self.build_link_on_exist_data('', 'page')
        link_sort = self.build_link_on_exist_data(link, 'attribute')
        link_sort = self.build_link_on_exist_data(link_sort, 'attribute_value')

        keys = {
            'date_create': _('date added'),
            'year_release': _('year release'),
            'popular': _('popular'),
            'sort': _('in trend'),
            'like': _('by rating')
        }
        context['link_sort'] = [(value, self.build_link(
            link_sort, 'sort', key)) for key, value in keys.items()]

        link = self.build_link_on_exist_data('', 'sort')
        link = self.build_link_on_exist_data(link, 'attribute')
        link = self.build_link_on_exist_data(link, 'attribute_value')

        context['sort'] = keys.get(self.request.GET.get('sort'), 'date_create')

        if self.request.GET.get('sort') == 'like':
            queryset = queryset.annotate(
                diff_like=F('like') - F('not_like')).order_by('-diff_like')
        elif self.request.GET.get('sort', ''):
            queryset = queryset.order_by('-%s' % self.request.GET.get('sort'))
        else:
            queryset = queryset.order_by('sort')

        items = queryset
        paginator = Paginator(items, 24)
        paginator.link = link

        try:
            context['items'] = paginator.page(page)
        except PageNotAnInteger:
            context['items'] = paginator.page(1)
        except EmptyPage:
            context['items'] = paginator.page(paginator.num_pages)

        return context

    def build_link(self, link, param, value):
        link += '&' if link else '?'
        link += '%s=%s' % (param, value)
        return link

    def build_link_on_exist_data(self, link, param):
        if self.request.GET.get(param, ''):
            link += '&' if link else '?'
            link += '%s=%s' % (param, self.request.GET.get(param))
        return link

    def get_queryset(self):
        qs = super(DetailGroupView, self).get_queryset()

        return qs.\
            filter(enable=1).prefetch_related('attributes', 'attributes__children')

    def get_template_names(self):
        if self.object.parent:
            return super(DetailGroupView, self).get_template_names()
        return ['materials/main_group_detail.html']


class DetailItemView(SingleObjectMixin, FormView):
    model = Item
    form_class = CommentForm
    template_name = 'materials/item_detail.html'

    def get_queryset(self):
        qs = super(DetailItemView, self).get_queryset()
        return qs\
            .filter(enable=1)\
            .select_related('creator', 'main_group')\
            .prefetch_related('main_group__groups', 'comments', 'comments__user', 'recommend_item', 'images',
                              'item_attr__attribute', 'item_attr__attribute_values')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        slug = self.kwargs.get('slug', None)

        if slug is not None:
            self.kwargs['slug'] = self.kwargs['slug'].split('/').pop()
        return super(DetailItemView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return redirect('/login/?next=%s' % request.path)
        self.object = self.get_object()

        form = self.get_form()
        if form.is_valid():
            comment = form.save(commit=False)
            comment.object_id = self.object.pk
            comment.content_type = ContentType.objects.get_for_model(
                self.model)
            comment.user = request.user

materials/templates/materials/attribute_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ object.title }}{% endblock %}

{% block main %}
    <div class="wrapp category">
        <h1>{{ object.title|capfirst }}</h1>
        <a href="{{ back }}">Назад к {{ group }}</a>

        <div class="row list-item">
            {% for value in attribute_values %}
                <div class="col-md-6">
                    <div class="value">
                        <a class="{% if value.active %}active {% endif %}btn btn-block btn-default btn-sm" href="{{ value.link }}">{{ value.title }}</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

materials/templates/materials/group_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ object.title }}{% endblock %}

{% block main %}
    <div class="wrapp category">
        <div class="row">
            <div class="col-xs-24">
                <h1>{{ object.title|capfirst }}</h1>
            </div>

            {% for attribute in object.attributes.all %}
                <div class="col-md-4">
                    <div class="heading">
                        {% if attribute.icon %}
                            <span class="glyphicon glyphicon-{{ attribute.icon }}" aria-hidden="true"></span>
                        {% endif %}
                        {{ attribute.title }}
                    </div>
                    {% for children in attribute.children.all %}
                        <a href="{{ children.link }}" class="{% if children.active %}active {% endif %}btn btn-block btn-default btn-sm">
                            <span class="block text-left">{{ children.title }}</span>
                        </a>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>

    {% if items_popular %}
        <div class="menu">
            <div class="row wrapp now">
                <div class="col-xs-24">
                    <h3>
                        Самое просматриваемое прямо сейчас
                    </h3>
                </div>

                {% for item in items_popular %}
                    <div class="col-md-3 col-sm-4 col-xs-6">
                        <a href="{{ item.get_absolute_url }}">
                            {% if item.original_image %}
                                <img title="{{ item.title }}" alt="{{ item.title }}" class="img-responsive shadow" src="{{ item.original_image }}">
                            {% endif %}
                            <div class="title">{{ item.title|truncatechars:12 }}</div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <div class="wrapp list-item">
        <div class="row">
            <div class="col-md-12">
                {% block breadcrumbs %}
                    <ol class="breadcrumb">
                        {% for group in breadcrumbs %}
                            <li><a href="{{ group.get_absolute_url }}">{{ group.title|capfirst }}</a></li>
                        {% endfor %}
                        <li class="active"><a>{{ object.title|capfirst }}</a></li>
                    </ol>
                {% endblock %}
            </div>
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-8">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                {{ sort }}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                {% for text, link in link_sort %}
                                    <li><a href="{{ link }}">{{ text }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-8 text-right">
                        <button class="btn btn-default active"><span class="glyphicon glyphicon-th"></span></button>
                        <button class="btn btn-default"><span class="glyphicon glyphicon-th-list"></span></button>
                    </div>
                </div>
            </div>
        </div>

        {% if items %}
            <div class="row group">
                {% for item in items %}
                    <div class="col-md-4 item">
                        <a href="{{ item.get_absolute_url }}">
                            <img class="img-responsive shadow-item" src="{{ item.original_image }}">
                            <div class="empty"></div>
                            <div class="short_title">
                                <span>{{ item.title|truncatechars:33 }}</span>
                            </div>
                            <div class="full_title">
                                <div class="title"><span>{{ item.title|truncatechars:50 }}</span></div>
                                <div class="short_desc">
                                    <span>{{ item.year_release|date:'Y' }}</span>
                                <span>
                                    {% with countries=item.countries.all|join:', ' %}
                                        {% if countries %}
                                            &bull; {{ countries|truncatechars:"50" }}
                                        {% endif %}
                                    {% endwith %}
                                </span>
                                </div>
                                <div class="bottom">
                                    <div class="like pull-left">{{ item.like }}</div>
                                    <div class="not-like pull-left">{{ item.not_like }}</div>
                                    <div class="quality pull-right text-right">
                                        <span class="hd"></span>
                                        <span class="hq"></span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>

            <nav>
                <ul class="pagination pagination-lg">
                    {% if items.has_previous %}
                        <li>
                            <a href="?page={{ items.previous_page_number }}{{ items.paginator.link }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for page in items.paginator.page_range  %}
                        <li {% if page == items.number %}class="active" onclick='return false;'{% endif %}>
                            <a href="?page={{ page }}{{ items.paginator.link }}">{{ page }}</a>
                        </li>
                    {% endfor %}

                    {% if items.has_next %}
                        <li>
                            <a href="?page={{ items.next_page_number }}{{ items.paginator.link }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
{% endblock %}

materials/templates/materials/item_edit.html
{% extends "base.html" %}
{% load i18n %}
{% load filter_extra %}
{% load staticfiles %}

{% block title %}{{ object.title }}{% endblock %}

{% block main %}
    <div class="wrapp item-edit" ng-app="edit-item">
        <a href="{{ object.get_absolute_url }}">
            <h1>{{ object.title|capfirst }}</h1>
        </a>

        <form enctype="multipart/form-data" validate action="{% url 'materials:item_edit' object.slug %}" name="{{ form.form_name }}" method="post" >
            {% csrf_token %}
            <div class="row" id="model_name">
                <div class="col-md-5">
                    {{ form.original_image.errors }}
                    {{ form.original_image }}
                </div>
                <div class="col-md-19" >
                    <div class="row fieldWrapper">
                        <div class="col-xs-12">
                            <div class="label_tag_field">{{ form.title.label_tag }}</div>
                            <div class="value_field">{{ form.title }}</div>
                            <div class="error_field">{{ form.title.errors }}</div>
                        </div>
                        <div class="col-xs-12">
                            <div class="label_tag_field">{{ form.origin_title.label_tag }}</div>
                            <div class="value_field">{{ form.origin_title }}</div>
                            <div class="error_field">{{ form.origin_title.errors }}</div>
                        </div>
                    </div>
                    <div class="row fieldWrapper">
                        <div class="col-xs-7">
                            {{ form.genres.label_tag }}
                            {{ form.genres.errors }}
                        </div>
                        <div class="col-xs-17">
                            {{ form.genres }}
                        </div>
                    </div>
                    <div class="row fieldWrapper">
                        <div class="col-xs-7">
                            {{ form.countries.label_tag }}
                            {{ form.countries.errors }}
                        </div>
                        <div class="col-xs-17">
                            {{ form.countries }}
                        </div>
                    </div>
                    <div class="row fieldWrapper">
                        <div class="col-xs-7">
                            {{ form.description.label_tag }}
                            {{ form.description.errors }}
                        </div>
                        <div class="col-xs-17">
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="row fieldWrapper">
                        <div class="col-xs-7">
                            {{ form.year_release.label_tag }}
                            {{ form.year_release.errors }}
                        </div>
                        <div class="col-xs-17">
                            {{ form.year_release }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-24 text-center">
                    <button type="submit" class="btn btn-primary pull-right">{% trans 'Submit' %}</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'client/src/js/ng-django-forms.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        angular.module('edit-item', ['ng.django.forms']);
    </script>
{% endblock scripts %}

materials/templates/materials/main_group_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ object.title }}{% endblock %}

{% block main %}
    <div class="wrapp category">
        <div class="row main_category">
            <div class="col-xs-3">
                <h1>{{ object.title|capfirst }}</h1>
            </div>

            {% for group in object.groups.all %}
                <div class="col-xs-4">
                    <a href="{{ group.get_absolute_url }}">
                        <div class="sub-cat">
                            <span class="film" aria-hidden="true"></span>
                            <span class="text">{{ group.title|capfirst }}</span>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    {% if items_popular %}
    <div class="menu">
        <div class="row wrapp now">
            <div class="col-xs-24">
                <h3>
                    Самое просматриваемое прямо сейчас
                </h3>
            </div>

            {% for item in items_popular %}
                <div class="col-md-3 col-sm-4 col-xs-6">
                    <a href="{{ item.get_absolute_url }}">
                        {% if item.original_image %}
                            <img title="{{ item.title }}" alt="{{ item.title }}" class="img-responsive shadow" src="{{ item.original_image }}">
                        {% endif %}
                        <div class="title">{{ item.title|truncatechars:12 }}</div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endblock %}

materials/templates/materials/play_video.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans object.title %}{% endblock %}

{% block main %}
    {% autoescape off %}
        {{ object.video }}
    {% endautoescape %}
{% endblock %}