ex_user/urls.py
__author__ = 'igor'

from django.conf.urls import include, url
from ex_user.views import ExUser, ExUserRegistrationFormView


urlpatterns = [
    url(r'^$', ExUser.as_view(), name='profile'),
    url(r'^registration/$', ExUserRegistrationFormView.as_view(), name='registration'),
]

fs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from fs import settings
from django.conf.urls.static import static
from fs.views import IndexView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # url(r'^search/', include('haystack.urls')),
    url(r'^search/',
        include('search.urls', app_name='search', namespace='search')),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^profile/',
        include('ex_user.urls', app_name='ex_user', namespace='ex_user')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^materials/',
        include('materials.urls', app_name='materials',
                namespace='materials')),
    url(r'^comments/',
        include('comments.urls', app_name='comments', namespace='comments')),
    url(r'^admin/', include(admin.site.urls)),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ex_user/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from materials.models import Item


class ExUser(models.Model):
    user = models.OneToOneField(User, related_name='ex_user')
    img = models.ImageField(verbose_name=_('Image'), upload_to='images/ex_user/', blank=True)
    liked = models.ManyToManyField(Item, verbose_name=_('My Favorites'), related_name='users_liked')
    defer = models.ManyToManyField(Item, verbose_name=_('For the future'), related_name='users_defer')
    like_item = models.ManyToManyField(Item, verbose_name=_('Like this'), related_name='user_like')
    not_like_item = models.ManyToManyField(Item, verbose_name=_('Not like this'), related_name='user_not_like')

    class Meta:
        verbose_name = _('Extend user')
        verbose_name_plural = _('Extends user')

    def img_preview(self):
        if self.img:
            return u'<img src="%s" style="max-width:100px; max-height:100px" >' % self.img.url
    img_preview.short_description = _('Image')
    img_preview.allow_tags = True

ex_user/forms.py
__author__ = 'igor'
from ex_user.models import ExUser
from django import forms
from django.contrib.auth.models import User
from djangular.styling.bootstrap3.forms import Bootstrap3Form
from djangular.forms import NgFormValidationMixin, NgModelForm
from django.utils.translation import ugettext_lazy as _


class UserMeta(type(NgModelForm), type(Bootstrap3Form)):
    pass


class ExUserForm(NgModelForm, NgFormValidationMixin, Bootstrap3Form):
    __metaclass__ = UserMeta
    form_name = 'ex_user_form'
    scope_prefix = 'ex_user_model'

    class Meta:
        model = ExUser
        fields = ['img']


class UserForm(NgModelForm, NgFormValidationMixin, Bootstrap3Form):
    __metaclass__ = UserMeta
    form_name = 'user_form'
    scope_prefix = 'user_model'

    def __init__(self, **kwargs):
        super(UserForm, self).__init__(**kwargs)
        self.fields['password'].help_text = ''

        for name, type_field in self.fields.items():
            for error, message in type_field.get_potential_errors():
                if message.capitalize() and not self.fields[name].help_text:
                    self.fields[name].help_text += message.capitalize()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

ex_user/views.py
from ex_user.forms import ExUserForm, UserForm
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login


class ExUser(TemplateView):
    template_name = 'ex_user/profile.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return redirect('/login/?next=%s' % request.path)
        return super(ExUser, self).get(request, *args, **kwargs)


class ExUserRegistrationFormView(FormView):
    template_name = 'ex_user/registration.html'
    success_url = '/profile/'
    form_class = UserForm
    ex_user_form = ExUserForm

    def forms_valid(self, request, **kwargs):
        user = authenticate(username=kwargs['username'], password=kwargs['password'])

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(self.get_success_url())
            raise Exception('Account disabled')
        raise Exception('invalid login')

    def forms_invalid(self, form_user, form_ex_user):
        return self.render_to_response(self.get_context_data(form_user=form_user, form_ex_user=form_ex_user))

    def post(self, request, *args, **kwargs):
        user_form = self.get_form()
        form_ex_user = self.ex_user_form(self.request.POST, self.request.FILES)

        if user_form.is_valid() and form_ex_user.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()
            ex_user = form_ex_user.save(commit=False)
            ex_user.user = user
            ex_user.save()
            return self.forms_valid(request, username=self.request.POST.get('username'),
                                    password=self.request.POST.get('password'))
        return self.forms_invalid(user_form, form_ex_user)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(reverse('ex_user:profile'))

        return super(ExUserRegistrationFormView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = dict()
        context['form_user'] = self.get_form()
        context['form_ex_user'] = self.ex_user_form()
        context.update(super(ExUserRegistrationFormView, self).get_context_data(**kwargs))
        return context

    def get_success_url(self):
        return self.success_url

ex_user/templates/ex_user/profile.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans 'Profile' %}{% endblock %}

{% block main %}
    <div class="wrapp" ng-app="profile">
        <h1>Welcome, {{ user }}</h1>
        <div class="row" ng-controller="Tabs">
            <div class="col-md-5">
                {% if user.ex_user.img %}
                    <div class="image">
                        <img class="img-user img-responsive img-rounded" src="{{ user.ex_user.img.url }}">
                    </div>
                {% endif %}
                <div class="password_change">
                    <a href="{% url 'password_change' %}">password change</a>
                </div>
            </div>
            <div class="col-md-19" >
                <div ng-init="tabList=['Favorite', 'Defer']">
                    <ul class="nav nav-tabs" role="tablist">
                        <li ng-repeat="tab in tabList" ng-class="tabClass(tab)">
                            <a ng-click="setTab(tab)" ng-bind="tab"></a>
                        </li>
                    </ul>
                </div>

                <div class="tab-content">
                    <div ng-show="activeTab==='Favorite'">
                        <div class="list-item">
                            <div class="row group">
                                {% for item in user.ex_user.liked.all %}
                                    <div class="col-xs-4 item">
                                        <a href="{{ item.get_absolute_url }}">
                                            <img class="img-responsive shadow-item" src="{{ item.original_image }}">
                                            <div class="empty"></div>
                                            <div class="short_title">
                                                <span>{{ item.title|truncatechars:33 }}</span>
                                            </div>
                                            <div class="full_title">
                                                <div class="title"><span>{{ item.title|truncatechars:50 }}</span></div>
                                                <div class="short_desc">
                                                    <span>{{ item.year_release|date:'Y' }}</span>
                                                    <span>
                                                        {% with countries=item.countries.all|join:', ' %}
                                                            {% if countries %}
                                                                &bull; {{ countries|truncatechars:"50" }}
                                                            {% endif %}
                                                        {% endwith %}
                                                    </span>
                                                </div>
                                                <div class="bottom">
                                                    <div class="like pull-left">{{ item.like }}</div>
                                                    <div class="not-like pull-left">{{ item.not_like }}</div>
                                                    <div class="quality pull-right text-right">
                                                        <span class="hd"></span>
                                                        <span class="hq"></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div ng-show="activeTab==='Defer'" >
                        <div class="list-item">
                            <div class="row group">
                                {% for item in user.ex_user.defer.all %}
                                    <div class="col-xs-4 item">
                                        <a href="{{ item.get_absolute_url }}">
                                            <img class="img-responsive shadow-item" src="{{ item.original_image }}">
                                            <div class="empty"></div>
                                            <div class="short_title">
                                                <span>{{ item.title|truncatechars:33 }}</span>
                                            </div>
                                            <div class="full_title">
                                                <div class="title"><span>{{ item.title|truncatechars:50 }}</span></div>
                                                <div class="short_desc">
                                                    <span>{{ item.year_release|date:'Y' }}</span>
                                                    <span>
                                                        {% with countries=item.countries.all|join:', ' %}
                                                            {% if countries %}
                                                                &bull; {{ countries|truncatechars:"50" }}
                                                            {% endif %}
                                                        {% endwith %}
                                                    </span>
                                                </div>
                                                <div class="bottom">
                                                    <div class="like pull-left">{{ item.like }}</div>
                                                    <div class="not-like pull-left">{{ item.not_like }}</div>
                                                    <div class="quality pull-right text-right">
                                                        <span class="hd"></span>
                                                        <span class="hq"></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'ex_user/js/app.js' %}" ></script>
{% endblock scripts %}

ex_user/templates/ex_user/registration.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}


{% with title="Registration" %}
    {% block title %}{% trans title %}{% endblock %}

    {% block main %}
        <div class="wrapp" ng-app="registration">
            <h1>{{ title }}</h1>
            <form class="form_registration" enctype="multipart/form-data" name="{{ form_user.form_name }}" method="post" novalidate action="{% url 'ex_user:registration' %}" >
                {% csrf_token %}
                {{ form_user.as_div }}
                {{ form_ex_user.as_div }}
                <button type="submit" ng-disabled="{{ form_user.form_name }}.$invalid" class="btn btn-primary pull-right">{% trans 'Submit' %}</button>
            </form>
        </div>
    {% endblock main %}
{% endwith %}

{% block scripts %}
    <script src="{% static 'client/src/js/ng-django-forms.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        angular.module('registration', ['ng.django.forms']);
    </script>
{% endblock scripts %}